site_name: MCS Industries - CT
nav:
  - General: index.md
  - Home: home.md
  - Category: category.md
  - Product: product.md
  - Brand: brand.md
  - Static: static.md
  - Other: other.md
theme: readthedocs
extra_css:
  - style.css
